### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [dajare/robert-louis-stevenson_the-master-of-ballantrae#1]
Good job as always. A couple of things I'll ask Alex about, as I'm not sure about them, either. (And as we know, I rarely guess correctly, i.e. "according to Alex".)

- [x] I don't think we want the two lint errors to be covered over in an ignore file, mainly because I don't think they're regular paragraphs. As you note, they're "subheadings," although really they're _headers_ of what follows. And what follows are (long) quotes from a person's memoirs, thus making them blockquotes, and blockquotes have headers. Now, since the blockquotes are almost the entire chapter in both cases, it's OK to relax the left/right margins in CSS with something like `#chapter-3 blockquote {margin: …}`, assuming there isn't a blockquote _within_ the blockquote of either chapter (you would add the #chapter-7 selector as well).
- [x] I don't think we want to convert the M<sup>r</sup> to "Mr", either. A reader is going to do the same thing that typogrify is doing, and assume it's the standard abbreviation for Mister. (As you know, English don't typically include the full-stop after the Mr, so it's not unusual to see it like that.) So, either we leave it as M<sup>r</sup>, or we convert it to Master. I took a quick look through the corpus, and Robin kept the M<sup>r</sup> in several places in _Pepys_, but they all appear to be for Mister rather than Master. (Which just complicates things further.) I personally would probably convert them to Master for clarity, but I'm not sure that's what Alex would do. I'll ask him on the list.
- [x] You referenced "z3998:annotation" in your note on the list, but that is not present anywhere in the text. Which is just as well, as that is definitely not an annotation. :)
- [x] This is more guideline than rule (spot the movie quote!), but we try to keep our "standard" CSS together and marked as such (`/* letters */` `/* end of letters /*`), separate from the book-specific CSS. So, e.g., the letter and poem/verse CSS would be first in local.css, with all of the book-specific CSS following. As I said, guideline more than rule, but it makes it easier to see what's what, i.e. what's standard SE CSS and what's custom CSS, for reviewers and especially for Alex.
- [x] There are missing thematic breaks, e.g. ch. 10 p. 198, 206. I know some are present as well, but given the missing ones it's worth making a pass through the entire book to see if there are others missing. (You could also look at the Gutenberg source; it looks like the transcription marked the paragraphs following the breaks with a different class.) (Later: I saw at least one in ch. 6 as well while I was looking at formatting, so a full pass is definitely needed.)
- [x] ultima ratio is in M-W and therefore should not be tagged.
- [x] The "I were liker a man…" quote doesn't look/sound like emphasis to me. Wouldn't that be another `<q>`?
- [x] The preface is fiction; Stevenson made it up for a later edition of the book. I was curious whether fictional frontmatter would still be considered frontmatter, but there are oodles (technical term) of it in the corpus, so I guess it is.
- [x] There should be a space between name initials (unlike initialisms), e.g. E.McK. should be E. McK. at the end of ch. 7.
- [x] Based on a quick search, it appears that Ballantrae is a place, i.e. "Master of Ballantrae" is referring to the master of a place, is that correct? If so, while it may be a last name as well, instances of "Master of Ballantrae" are referring to the place not the name, so the "B." in "Master of B." would be just an abbreviation, not a surname.
- [x] The M. of M. de Voltaire should have a no-break-space between it and the "de", just like the Mr. of Mr. Hobbes.
- [x] I'm not sure the editor's note in ch. 6 should be a thematic break; that doesn't sound semantically correct to me. I also don't know that we should get rid of the brackets; that's pretty standard for editor's notes, even if this is a "fake" one. I'll add that to what I ask Alex about.
- [x] You don't need the "eoc" on the initials on the inscription at the end; they're the beginning of the sentence, not the end (hence the `<br/>` at the end of the line instead of a `</p>`). (Nice job on the line between the two!)
- [x] The two-line rhyme in ch. 1 is marked as poem and the four-line immediately following as verse. Why do you think they're different, i.e. the first complete and the second not?
- [x] I know the "ye ugly⸺" in ch. 2 doesn't have a space in front of the dash, but don't you think that's obfuscation, i.e. that she completes the "ugly …" phrase? I don't see any indication that she cuts it off, or is cut off. A judgment call, to be sure, so I'll leave it with you. If you think it is, then it's a 3em dash and should have a space after ugly.
- [x] The datelines on the letters are not right-justified, i.e. they're not flush right with the rest of the letter. The footers are, so there's something interfering with the datelines; you might have to debug it by looking at them in a browser and viewing the web inspector.
- [x] And, in the case of the one in ch. 6, the salutation isn't fully left-justified, either.
- [x] It doesn't appear the second line of the verse in ch. 11 ("The wind sall blaw…") is indented in the scans. Is there a reason it is in the book?

**Comment by dajare** [comment]
@vr8hub - Many thanks for this thorough review, Vince! I really appreciate your patient explanations, and your encouragement. I've "accepted" all these (or, I meant to!). By way of feedback at few places....

- cc 3 and 7 chapter "headers": I hope my adjustments have met the need. I see much better now how this should have worked. My adjustments might not pass muster, though. :/
- the "Alex judgments": (1) `M^r^` to `Master` was easy (\[Editorial\]); (2) the c6 "editorial note" has been modified to match the page scans, which I hope was the intention.
- the missing `<hr/>`s: how did I manage that?! There was a bucket-load of them, and I have a high degree of confidence that they're now all in place.
- `local.css` conventions: I've done my best to follow those guidelines (and I'm abysmally ignorant when it comes to films, so letting you down on the quote-spotting). I compared with (one of?) your Dumas repo(s?). **N.b.** I wasn't sure whether it was better to replicate the same rule in different "sections" for sake of clarity, or group all selectors for the same rule in one place. I opted for the former. This only affects `<q>`, I think, as calling for italics. I might have guessed wrong.
- I *think* all the rest are straightforward and appropriately "fixed", and don't call for comment.

Frankly, I thought this was going to be a much bigger disaster than this. It still wouldn't surprise me if you spot some more tweaks needed. If you're happy (you might not be!), then over to Alex.

This was a real stretch from my Trollope "comfort zone"—although I'm already proofing this Henry James I've just started, perhaps my fastest from initial-commit-to-proof yet! I note you got the last Father Brown collection done in 27 commits. I'm a long, long way from that sort of elegance, but improving ... I hope! 😬

**Comment by vr8hub** [comment]
Very good, all the changes look good, with these minor exceptions… (and which include a couple of things I missed the first time).
- [ ] The preface is still marked as non-fiction.
- [ ] I think it's fine to relax the left/right margins on the ch 3/7 blockquotes to 0, i.e. same as normal text. The header and the vertical margin are enough to tell us it's a quote, and that is what's usually done for chapter-length quotes like that. (_Clarissa_ and _Dangerous Liaisons_ both do that for all of their letters, e.g.)
- [ ] The ch 10/12 :before CSS has two margin elements, so only the second is being used. The first one can be deleted.
- [ ] In the case of those blockquotes, there is CSS for just the blockquote, and then CSS for `blockquote p`. Those can actually be combined into just the `blockquote p`: although the `font-variant` and `text-align` works on the blockquote as a whole, the `text-indent` doesn't (it's saying don't indent the _blockquote_, where what we want is to not indent the paragraphs _in_ the blockquote) and since there are only p's in the blockquote, then it can all be consolidated into just the `blockquote p`. IOW, just change the `blockquote{` to `blockquote p`, and delete the existing `blockquote p`, and it should yield the same result. Make sure, of course; one can never be sure when I'm talking out of my hat.
- [ ] This is _purely_ a preference, so I should just shut up, but I would put the italic on the chapter-6 nth-of-type(64) with its margin CSS, rather than with the other italics. If there were no other CSS needed but the italic, combining them would be great. But in this case, I think it's clearer to see everything that's going on with that paragraph in one place. This is one of those that Alex might rearrange anyway, so don't feel like you have to listen to me. :)

You underestimate yourself; you do great work. The Father Brown's were easy books; I probably should have left them for first-timers, but they were sentimental since one of his was the first thing I did at SE. And # of commits is definitely not a metric we want to pay attention to: I had 400+ on both Gibbon and Maupassant. :) Commits are free, so we don't really care how many it takes to get it right. As long as we don't mix editorial/non-editorial… lol

**Comment by dajare** [comment]
@vr8hub - Okay, all done (including the last re: `nth-of-type(64)`  — I listened!). I do see what you mean about clarity here.

Again, really grateful for the encouragement. Your Gibbon in particular is a work of supreme supererogation! Incredible. I'm beginning to entertain thoughts of doing Trollope's short fiction (there isn't an "omnibus collection" of them anywhere). Maybe I should stare at your Maupassant before going too far down that road. 😆 

Anyway! Does this get this RLS over the line? As ever, I live in hope. And thanks again, Vince!

**Comment by vr8hub** [comment]
I don't think you pushed the changes to GitHub?

**Comment by dajare** [comment]
@vr8hub  Urgghh!! 🤦‍♂️ I've done that once before. So sorry!

**Comment by vr8hub** [comment]
Good grief. I'm not very observant; I didn't notice that the italics for the editor's note was on a span; I thought we were combining the two elements, or I wouldn't have had you move it.

But now that I (finally) see that, we don't need that italic at all (in CSS). If it's going to be italicized, better to just do it with an unsemanticated italic (`<i>`) than have to use CSS to accomplish the same purpose. We don't generally use unsemanticated italics, but there are times when they are what's called for. So sorry myself! I didn't notice that before, and I've taken you on a merry goose chase.

With that one change (the `<span>` to an `<i>`, remove the italic CSS for the editor's note), it should be ready to go. And remember, Alex will likely change _something_, if not _multiple_ somethings. We never get it completely "right." :)

**Comment by dajare** [comment]
Tweaks made, changes pushed 😉 ! ("... not very observant" : a phrase I've never associated with @vr8hub)

Thanks again!
